{% set name = "exn" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exn-{{ version }}.tar.gz
  sha256: f50ee56999a7080a59788506282ec649e996c86be84a643909ff6a06c498e339

build:
  entry_points:
    - exn = exn.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - exonote
    - jesth
    - suggestion
    - gaspium
    - viewstack
    - viewable

test:
  imports:
    - exn
  commands:
    - pip check
    - exn --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/exn
  summary: Write and render rich, scriptable, and interactive notes 
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
